config/routes.rb
Rails.application.routes.draw do
  root 'home#portfolio'
  get 'home/top'
  get 'home/about'
  get 'home/login'
  get 'home/top'
  get 'admin/home/top'
  get 'coupons/index'
  devise_for :admins
  devise_for :users
  get 'users/withdrawal', to: 'users#withdrawal'
  put '/users/:id/hide' => 'users#hide', as: 'users_hide'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update]
  resources :items, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :new, :create]
    resources :materials, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :item
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :favorites,dependent: :destroy
  def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
  end

  has_many :coupons
  attachment :image
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :order_materials
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_materials
  accepts_nested_attributes_for :order_materials
end

app/models/order_material.rb
class OrderMaterial < ApplicationRecord
  belongs_to :material
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy

  def name
  	  first_name + last_name
  end

  def active_for_authentication?
  	  super && (self.deleted_at == false)
  end

  def self.search(search)
    if search
      where(['first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%"])
    else
      all
    end
  end

  attribute :user_status, :string, default: '有効'
  attribute :deleted_at, :boolean, default: 'false'

end

app/controllers/admin/materials_controller.rb
class Admin::MaterialsController < ApplicationController
  before_action :admin_user
  def index
  	  @materials = Material.all.order("genre DESC")
      @material = Material.new
  end

  def edit
  	  @material = Material.find(params[:id])
  end

  def create
  	  @material = Material.new(material_params)
  	  @material.save
  	  redirect_to admin_materials_path
  end

  def update
  	  @material = Material.find(params[:id])
  	  @material.update(material_params)
  	  redirect_to admin_materials_path
  end

  private
  def material_params
  	  params.require(:material).permit(:genre, :name)
  end

  def admin_user
  	  unless admin_signed_in?
  	  redirect_to root_path
  	  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
	def after_sign_in_path_for(resource)
	  case resource
	  when Admin
	  	admin_home_top_path
	  when User
	    items_path
	  end
	end


	def after_sign_out_path_for(resource_or_scope)
		url = request.referer
	    if url.include?("admin")
	      new_admin_session_path
	    else
	      home_top_path
	    end
	end

	def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :birthday, :address, :password, :password_confirmation])
    end

end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :authenticate_user!
  def index
    @item_ranking = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  	@user = current_user
  end

  private
  def item_params
  	params.require(:item).permit(:name, :text, :price, :image, :sale_status)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
      @item = Item.find(params[:item_id])
      favorite = current_user.favorites.new(item_id: @item.id)
      favorite.save
  end

  def destroy
  	  @item = Item.find(params[:item_id])
  	  favorite = current_user.favorites.find_by(item_id: @item.id)
  	  favorite.destroy
  end

  private
  def correct_user
      if user_signed_in?
         user = User.find(params[:id])
         if current_user.id != user.id
            redirect_to root_path
         end
      end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end

  def portfolio
      render :layout => 'portfolio'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
      @items = Item.all
      @item_ranking = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def show
  	  @item = Item.find(params[:id])
  end

  private
  def item_params
  	  params.require(:item).permit(:name, :text, :price, :image, :sale_status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only:[:show, :edit, :hide, :update]
  def show
      @user = current_user
      @item_ranking = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         redirect_to user_path(@user.id)
      else
         render 'edit'
      end
  end

  def withdrawal
  end

  def hide
      @user = User.find(params[:id])
      @user.update(deleted_at: true)
      @user.update(user_status: '退会済')
      reset_session
      redirect_to root_path
  end

  private
  def user_params
      params.require(:user).permit(:first_name, :last_name, :birthday, :address, :user_status, :email)
  end

  def correct_user
      if user_signed_in?
         user = User.find(params[:id])
         if current_user.id !=  user.id
            redirect_to root_path
         end
      end
  end

end

app/helpers/admin/materials_helper.rb
module Admin::MaterialsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/materials/edit.html.erb
<div class="container">
  <div class="row">
    <h2 style="text-align: center; margin-top: 50px;">食材・備品編集</h2>
      <div class="font_info">
        <div class="col-xs-10 col-xs-offset-1">
          <div style="text-align: center;">
            <%= form_for(@material, url: admin_material_path) do |f| %>
              <%= f.label :ジャンル %>
              <%= f.select :genre,options_for_select([[@material.genre],['米・肉', '米・肉'],['野菜', '野菜'],['調味料','調味料'],['備品','備品'],['その他','その他']]) %>
              <%= f.label :名前 %>
              <%= f.text_field :name, required: true %>
              <%= f.submit '変更', class: "btn btn-primary" %>
             <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/admin/materials/index.html.erb
<div class="container">
  <div class="row">
    <h2 style="text-align: center; margin-top: 50px;">食材・備品一覧</h2>
      <div class="font_info">
        <div class="col-xs-10 col-xs-offset-1">
          <div style="text-align: center;">
            <%= form_for(@material, url: admin_materials_path) do |f| %>
              <%= f.label :ジャンル %>
              <%= f.select :genre,options_for_select([['米・肉', '米・肉'],['野菜', '野菜'],['調味料','調味料'],['備品','備品'],['その他','その他']]), class: "btn btn-info" %>
              <%= f.label :名前 %>
              <%= f.text_field :name, required: true %>
              <%= f.submit '追加', class: "btn btn-primary" %>
            <% end %>
          </div>

          <table class="table">
	          <thead>
		          <tr>
			          <th>ジャンル</th>
			          <th>名前</th>
		          </tr>
	          </thead>

	          <tbody>
		          <% @materials.each do |material| %>
		            <tr>
                  <td><%= material.genre %></td>
                  <td><%= material.name %></td>
                  <td><%= link_to "編集する", edit_admin_material_path(material.id), class: "btn btn-primary" %></td>
		            </tr>
		          <% end %>
	          </tbody>
          </table>
        </div>
      </div>
    <span id="back">
      <a href="#">
      </a>
    </span>
  </div>
</div>