config/routes.rb
Rails.application.routes.draw do
  root 'home#portfolio'
  get 'home/top'
  get 'home/about'
  get 'home/login'
  get 'home/top'
  get 'admin/home/top'
  get 'coupons/index'
  devise_for :admins
  devise_for :users
  get 'users/withdrawal', to: 'users#withdrawal'
  put '/users/:id/hide' => 'users#hide', as: 'users_hide'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update]
  resources :items, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :new, :create]
    resources :materials, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy

  def name
  	  first_name + last_name
  end

  def active_for_authentication?
  	  super && (self.deleted_at == false)
  end

  def self.search(search)
    if search
      where(['first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%"])
    else
      all
    end
  end

  attribute :user_status, :string, default: '有効'
  attribute :deleted_at, :boolean, default: 'false'

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  def index
  	  @users = User.all.page(params[:page]).reverse_order.per(10).search(params[:search])
  end

  def show
  	  @user = User.find(params[:id])
  end

  def edit
  	  @user = User.find(params[:id])
  end

  def update
  	  @user = User.find(params[:id])
  	  @user.update(user_params)
  	  redirect_to admin_user_path(@user)
  end

  private
  def user_params
  	  params.require(:user).permit(:first_name, :last_name, :note, :birthday, :address, :user_status, :email)
  end

  def admin_user
  	  unless admin_signed_in?
  	  redirect_to root_path
  	  end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only:[:show, :edit, :hide, :update]
  def show
      @user = current_user
      @item_ranking = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         redirect_to user_path(@user.id)
      else
         render 'edit'
      end
  end

  def withdrawal
  end

  def hide
      @user = User.find(params[:id])
      @user.update(deleted_at: true)
      @user.update(user_status: '退会済')
      reset_session
      redirect_to root_path
  end

  private
  def user_params
      params.require(:user).permit(:first_name, :last_name, :birthday, :address, :user_status, :email)
  end

  def correct_user
      if user_signed_in?
         user = User.find(params[:id])
         if current_user.id !=  user.id
            redirect_to root_path
         end
      end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <h2 style="text-align: center; margin-top: 100px;">会員編集</h2>

    <%= form_for @user, url: user_path(@user) do |f| %>
      <div class="col-xs-10 col-xs-offset-1">
        <table class="table">
          <tr>
            <th><%= f.label :氏名 %></th>
            <th>(姓)<%= f.text_field :first_name %>
                (名)<%= f.text_field :last_name %></th>
          </tr>

          <tr>
            <th><%= f.label :メールアドレス %></th>
            <th><%= f.email_field :email, class: "col-xs-10" %></th>
          </tr>

          <tr>
            <th><%= f.label :利用予定住所 %></th>
            <th><%= f.select :address, options_for_select([[@user.address],['六本木', '六本木'], ['銀座', '銀座'],['赤坂','赤坂']]), class: "btn btn-info" %></th>
          </tr>

          <tr>
            <th><%= f.label :誕生日 %></th>
            <th><%= @user.birthday.strftime('%-m月  %-d日') %></th>
          </tr>
        </table>

        <tr>
          <th><%= f.submit "変更を保存する", class: "btn btn-primary col-xs-3 col-xs-offset-3" %></th>
          <th><%= link_to "退会する", users_withdrawal_path(current_user), class: "btn btn-danger col-xs-3" %></th>
        </tr>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
	  <h2 style="text-align: center; margin-top: 100px;">会員詳細</h2>
	    <div class="col-xs-6 col-xs-offset-3">
	      <table class="table">
	        <tr>
		        <th>氏名</th>
		        <th><%= @user.name %></th>
	        </tr>

	        <tr>
		        <th>メールアドレス</th>
		        <th><%= @user.email %></th>
	        </tr>

	        <tr>
		        <th>利用予定住所</th>
		        <th><%= @user.address %></th>
	        </tr>

	        <tr>
            <th>誕生日</th>
	          <th><%= @user.birthday.strftime('%-m月  %-d日') %></th>
	        </tr>
	      </table>
        <%= link_to '編集する', edit_user_path(@user), class: "btn btn-primary col-xs-4 col-xs-offset-4" %>
      </div>

  	  <h3 style="text-align: center; margin-top: 30%; ">ご利用可能なクーポン</h3>

      <div class="col-xs-4">
  	    <%= attachment_image_tag @item_ranking.first, :image, :fill, 250, 250, fallback: "no_image.jpg" %>
  	  </div>

  	  	<div class="col-xs-7" style="margin-left: 5%;">
          <table class="table">
		        <tr>
			        <th>商品名</th>
	    	      <th><%= @item_ranking.first.name %></th>
	    	    </tr>
	      　</table>
					<p style="font-size: 30px; margin-left: 10%;">
					No.15680-<%= current_user.id %></br>
					お仕事応援クーポン</br>
					<%= @item_ranking.first.price %> 円 =>  <a style="font-size: 50px; color: #FF69A3; text-decoration: none;"><%= (@item_ranking.first.price - 50).to_i %> 円</a>
					</p>
					<div class="item_<%= @item_ranking.first.id %>">
						<%= render 'items/popular', item: @item_ranking.first %>
					</div>
					<div>
					<%= link_to 'クーポンページへ', coupons_index_path, :style=>"color: #000;" %>
					</div>
				</div>
  </div>
</div>

app/views/users/withdrawal.html.erb
<div class="container">
  <div class="center-block">
    <h2 style="text-align: center; margin-top: 100px;">本当に退会しますか？</h2>
      <p style="text-align: center; font-size: 20px;">退会すると誕生日割引やクーポンのご利用ができなくなります</p>

      <div><%= link_to '退会しない', user_path(current_user), class: "btn btn-info col-xs-3 col-xs-offset-3" %>
      	   <%= link_to '退会する', users_hide_path(current_user), data: { confirm: "本当に退会しますか？" }, method: :put, class: "btn btn-danger col-xs-3" %>
      </div>
  </div>
</div>