config/routes.rb
Rails.application.routes.draw do
  root 'home#portfolio'
  get 'home/top'
  get 'home/about'
  get 'home/login'
  get 'home/top'
  get 'admin/home/top'
  get 'coupons/index'
  devise_for :admins
  devise_for :users
  get 'users/withdrawal', to: 'users#withdrawal'
  put '/users/:id/hide' => 'users#hide', as: 'users_hide'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update]
  resources :items, only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :new, :create]
    resources :materials, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :item
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :favorites,dependent: :destroy
  def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
  end

  has_many :coupons
  attachment :image
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :order_materials
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_materials
  accepts_nested_attributes_for :order_materials
end

app/models/order_material.rb
class OrderMaterial < ApplicationRecord
  belongs_to :material
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy

  def name
  	  first_name + last_name
  end

  def active_for_authentication?
  	  super && (self.deleted_at == false)
  end

  def self.search(search)
    if search
      where(['first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%"])
    else
      all
    end
  end

  attribute :user_status, :string, default: '有効'
  attribute :deleted_at, :boolean, default: 'false'

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  def top
      @address1 = User.where(address:'六本木')
      @address2 = User.where(address:'赤坂')
      @address3 = User.where(address:'銀座')
  end

  private
  def admin_user
      unless admin_signed_in?
      redirect_to root_path
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
	def after_sign_in_path_for(resource)
	  case resource
	  when Admin
	  	admin_home_top_path
	  when User
	    items_path
	  end
	end


	def after_sign_out_path_for(resource_or_scope)
		url = request.referer
	    if url.include?("admin")
	      new_admin_session_path
	    else
	      home_top_path
	    end
	end

	def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :birthday, :address, :password, :password_confirmation])
    end

end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :authenticate_user!
  def index
    @item_ranking = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  	@user = current_user
  end

  private
  def item_params
  	params.require(:item).permit(:name, :text, :price, :image, :sale_status)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
      @item = Item.find(params[:item_id])
      favorite = current_user.favorites.new(item_id: @item.id)
      favorite.save
  end

  def destroy
  	  @item = Item.find(params[:item_id])
  	  favorite = current_user.favorites.find_by(item_id: @item.id)
  	  favorite.destroy
  end

  private
  def correct_user
      if user_signed_in?
         user = User.find(params[:id])
         if current_user.id != user.id
            redirect_to root_path
         end
      end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end

  def portfolio
      render :layout => 'portfolio'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
      @items = Item.all
      @item_ranking = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def show
  	  @item = Item.find(params[:id])
  end

  private
  def item_params
  	  params.require(:item).permit(:name, :text, :price, :image, :sale_status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only:[:show, :edit, :hide, :update]
  def show
      @user = current_user
      @item_ranking = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         redirect_to user_path(@user.id)
      else
         render 'edit'
      end
  end

  def withdrawal
  end

  def hide
      @user = User.find(params[:id])
      @user.update(deleted_at: true)
      @user.update(user_status: '退会済')
      reset_session
      redirect_to root_path
  end

  private
  def user_params
      params.require(:user).permit(:first_name, :last_name, :birthday, :address, :user_status, :email)
  end

  def correct_user
      if user_signed_in?
         user = User.find(params[:id])
         if current_user.id !=  user.id
            redirect_to root_path
         end
      end
  end

end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/home/top.html.erb
<div class="container">
  <div class="row">

    <%= link_to admin_users_path do %>
      <div class="box">
        <div class="root_box1">会員一覧
        </div>
      </div>
    <% end %>

    <%= link_to admin_items_path do %>
      <div class="box">
        <div class="root_box2">弁当一覧
        </div>
      </div>
    <% end %>

    <%= link_to admin_materials_path do %>
      <div class="box">
        <div class="root_box3">食材一覧
        </div>
      </div>
    <% end %>

    <%= link_to admin_orders_path do %>
      <div class="box">
        <div class="root_box4">発注一覧
        </div>
      </div>
    <% end %>

    <%= link_to home_top_path do %>
      <div class="box">
        <div class="root_box5">ホームページ
        </div>
      </div>
    <% end %>

    <%= link_to new_admin_order_path do %>
      <div class="box">
        <div class="root_box6">発注書作成
        </div>
      </div>
    <% end %>

    <h3 style="float: left; font-weight: bold;">ユーザーの住所登録数</h3>
      <div class="font_info" style="float: left; padding-top: 15px;
      margin-left: 30px;">
        六本木：<%= @address1.count %>
        赤坂：<%= @address2.count %>
        銀座：<%= @address3.count %>
      </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="about_phote">
  <p class="about_top">
  	いつもがんばるあなたへ
  </p>
  <p class="about_comment">
  	このサイトは懸命に仕事に打ち込むあなたへ</br>
  	お弁当をお届けするキッチンカー</br>
  	「Area42」を紹介するサイトです。
  </p>
</div>

app/views/home/portfolio.html.erb
<div class="portfolio_photo">
  <div class="portfolio_info">
  目次<br>
  プログラミング言語<br>
  ポートフォリオ紹介<br>
  プログラミングスクール<br>
  プロフィール<br>
  お問い合わせ<br>
  </div>
  <div class="portfolio_text">work</div>
</div>

  <div class="skill_photo">
    <div class="skill_title">skills</div><br>
    <div class="skill_text">
      HTML<br>
      CSS<br>
      JavaScript<br>
      Ruby<br>
      SQL<br>
      Ruby on Rails<br>
      jQuery<br>
    </div>
    <div class="detail_text">
    主にRuby on Railsを使った<br>
    プログラミングを勉強<br>
    今回開発したアプリケーションでは<br>
    独学とプログラミングスクールで<br>
    学んだことを
    余すことなく<br>
    実装、表現できるよう努めました<br>
    今後も理解を深めていくとともに<br>
    新たな言語にも挑戦していきたい
    </div>
  </div>

  <div class="web_box">
    <div class="web_title">
    portfolio
    </div>
      <div class="web_info">
        サイト名<br>
        <div class="text_info">Area42</div>
          概要<br>
          移動販売車(キッチンカー)での弁当の販売、閲覧サイト及び管理者側での運営管理<br>
          <br>
          テーマ<br>
          自身で移動販売車で営業することを想定したサイト<br>
          管理者側に重きをおいたwebアプリケーション<br>
          <br>
          テーマを選んだ理由<br>
          自分の考える将来やってみたいビジネスプランを具現化してみようと思い製作<br>
          <br>
          利用目的<br>
          顧客側<br>
          webページの閲覧が可能で登録することでクーポンなどが使えるようになる<br>
          <br>
          管理者側<br>
          販売する弁当の登録、編集ができる<br>
          登録しているユーザーの管理、検索が可能で個別にメモを取れるようになっている<br>
          発注書作成が可能で在庫や過去の発注を確認できる
      </div>
  </div>
      <div class="web_text">
      キッチンカーを紹介する<br>
      Webアプリケーション
      <div class="go">
      GO  ➡︎
      </div>
      </div>
      <%= link_to home_top_path do %>
        <div class="web_photo">
        </div>
      <% end %>

  <div class="school_photo">
    <div class="school_title">
    school
    </div>
    <div class="school_text">
      フロントエンド<br>
      HTML/CSS<br>
      Bootstrap<br>
      JavaScript/jQuery/Ajax<br>
      <br>
      サーバサイド<br>
      Ruby/Ruby on Rails<br>
      <br>
      その他<br>
      Rspec<br>
      SQL<br>
      <br>
      インフラ<br>
      AWS(EC2,RDS,ELB)<br>
      Vagrant/VirtualBox<br>
      <br>
      設計<br>
      画面設計、機能一覧<br>
      データベース設計(ER図)<br>
      アプリケーション詳細設計<br>
      <br>
      プロジェクト管理<br>
      チームビルディング、WBS管理<br>
      KPT、GitHub(チーム開発)
      <div class="detail_school_button">
        詳細表示
      </div>
    </div>
    <div class="detail_school_text">
      プログラミングスクールにて<br>
      基礎から勉強に励み<br>
      最終的に1人でのアプリケーション開発から<br>
      デプロイに至るまでの設定、工程を経験しました<br>
      また課せられた課題でのチーム開発にも挑み<br>
      周りとコミュニケーションを取りながら<br>
      期日までにアプリケーションを完成させる<br>
      実際の現場に近い経験をすることができました<br>
      実務は未経験ではありますが<br>
      このスクールで学んだことは<br>
      今後の自分の助けになり、<br>
      少しでも早く対応できるのではないかと<br>
      考えております<br>
      <br>
      今回のポートフォリオでは<br>
      もし自分が調理の道で食べていくとしたらをテーマに<br>
      リアリティのあるアプリケーション開発に<br>
      挑戦しました<br>
      管理者側の機能を充実させ<br>
      経験者だからこその視点を持って<br>
      製作することに注力しました<br>
    </div>
  </div>

  <div class="profile_box">
    <div class="profile_title">
    profile
    </div>
    <div class="profile_text">
    エンジニアを目指している理由<br>
    <br>
    日常生活において触れる機会の多くなった技術を身につけ、<br>
    今まで仕事を通して人へのサービスや気遣いを大事にしてきた<br>
    自分のマインドを落とし込むことにより<br>
    多くの人へサービスを提供することができるのではないかと考え、<br>
    エンジニアになる決意をしました。<br>
    前職でも顧客情報をデータで取り扱っていたのですが、<br>
    使い方や動作に不満を抱くこともあり<br>
    自分の手でより良いものにできないかと考えておりました。<br>
    今後もこういったサービスが増えていく中で自身も作り手の一員となり、<br>
    今まで培った知識や経験を生かして形として表現し、<br>
    仕事を通して人から感謝され喜ばれるものを作りたいと考えております。
    </div>
  </div>

  <div class="profile_info">
    山城　康平<br>
    1988/07/31<br>
  </div>
  <div class="profile_photo">
  </div>
  <div class="profile_detail">
  長きにわたり調理や販売などのサービス業に従事<br>
  顧客情報や在庫などの管理や<br>
  新人教育などの責任者業務を行っておりました<br>
  web開発やデザインに興味があり<br>
  サービスを形にしたい思いと自身の成長の為<br>
  プログラミングスクールに通学後<br>
  エンジニアを目指して勉強中です
  </div>

  <div class="contact_photo">
    <div class="contact_title">
      contact
    </div>
    <div class="contact_text">
    mushakora89br@gmail.com
    </div>
  </div>
  <span id="back">
    <a href="#">
    </a>
  </span>

app/views/home/top.html.erb
 <div class="top_phote">
  <p class="top_text">Area 42</p>
    <p class="top_comment">街の働き者を応援するキッチンカー
    </p>
    <p class="instruction">
  	  <%= link_to "menu", items_path, :style=>"color:#99FF99; text-decoration: none; " %>
    </p>
</div>